name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name:Gurukrishnaa
        id: snake-gif
      - name: Push to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: snake.svg
          path: dist/snake.svg
